name: CI

on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:

  stringspinner:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
    steps:
      - name: update container packages
        run: pacman -Syu --noconfirm
      - name: install dependencies
        run: |
          pkgs=(
            fmt
            gcc
            gcc-fortran
            git
            meson
            ninja
            pkgconf
            pythia8
            python
            perl
            tree
          )
          pacman -S --noconfirm ${pkgs[*]}
          echo "[+++++] PACKAGE VERSIONS:"
          for pkg in ${pkgs[@]}; do
            echo "$pkg: $(pacman -Qi $pkg | grep -E '^Version')"
          done
      - name: git checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: meson setup
        run: meson setup build --prefix=$(pwd)/install
      - run: meson install
        working-directory: build
      - run: tree install
      - run: meson test
        working-directory: build
      - name: test installation
        run: install/bin/clas-stringspinner --num-events 1
      - name: test OSG options
        run: install/bin/clas-stringspinner --trig 10 --docker --seed 1448577483 # see `clas12-mcgen` documentation
      - name: test relocatability
        run: |
          mkdir relocated
          cp -r install relocated/
          relocated/install/bin/clas-stringspinner --num-events 1
      - name: test symlinking
        run: |
          ln -sv install/bin/clas-stringspinner
          ./clas-stringspinner --num-events 1
      - name: generate documentation
        run: |
          mkdir publish
          .github/generate_usage_guide.sh install/bin/clas-stringspinner |& tee publish/index.html
      - name: upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          retention-days: 3
          path: publish/

  deploy_webpages:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: stringspinner
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: deployment
        id: deployment
        uses: actions/deploy-pages@v4
